---
output: 
  html_document:
    code_folding: hide
    message: FALSE
    warning: FALSE
runtime: shiny
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(shiny)


df <- read.csv("all_euro_data.csv")

df_2019 <- subset(df, seq(nrow(df)) >= 197413)

df_2019_cleaned <- df_2019[-(seq(1, 4726, by = 2)), ]

filtered_df <- subset(df_2019_cleaned, select = c("Div", "Date", "Time", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "HS", "AS", "HF", "AF"))

top_5_leagues = c("E0", "D1", "SP1", "I1", "F1")

filtered_df <- filtered_df[filtered_df$Div %in% top_5_leagues, ]

filtered_df <- mutate(filtered_df, Div = recode(Div, "E0" = "Premier League", "D1" = "Bundesliga", "SP1" = "La Liga", "I1" = "Serie A", "F1" = "Ligue 1"))


home_games <- filtered_df %>%
  count(Div, HomeTeam) %>%
  rename(Team = HomeTeam, HomeGames = n)

away_games <- filtered_df %>%
  count(Div, AwayTeam) %>%
  rename(Team = AwayTeam, AwayGames = n)

total_games <- full_join(home_games, away_games, by = c("Team", "Div"))

home_wins <- filtered_df %>%
  filter(FTR == "H") %>%
  count(Div,HomeTeam) %>%
  rename(Wins = n, Team = HomeTeam)

home_wins <- total_games %>%
  left_join(home_wins, by = c("Div", "Team")) %>%
  mutate(Wins = ifelse(is.na(Wins), 0, Wins))%>%
  rename(HomeWins = Wins)

away_wins <- filtered_df %>%
  filter(FTR == "A") %>%
  count(Div,AwayTeam) %>%
  rename(Wins = n, Team = AwayTeam)

away_wins <- total_games %>%
  left_join(away_wins, by = c("Div", "Team")) %>%
  mutate(Wins = ifelse(is.na(Wins), 0, Wins))%>%
  rename(AwayWins = Wins)

win_rates <- full_join(home_wins, away_wins, by = c("Team", "Div", "HomeGames", "AwayGames"))%>%
  mutate(HomeWinPct = (HomeWins / HomeGames) * 100, AwayWinPct = (AwayWins / AwayGames) * 100)

combined_data <- rbind(
  select(win_rates, Div, Team, WinPct = HomeWinPct)%>%
    mutate(Type = "Home"),
  select(win_rates, Div, Team, WinPct = AwayWinPct)%>%
    mutate(Type = "Away"))

combined_data$Type <- factor(combined_data$Type, levels = c("Home", "Away"))

filtered_df$FTHG <- as.numeric(as.character(filtered_df$FTHG))
filtered_df$FTAG <- as.numeric(as.character(filtered_df$FTAG))


home_goal_diff <- filtered_df %>%
  mutate(GoalDiffHome = FTHG - FTAG) %>%
  group_by(Div,HomeTeam) %>%
  summarise(HomeGoalDiff =mean(GoalDiffHome))%>%
  rename(Team = HomeTeam)


away_goal_diff <- filtered_df %>%
  mutate(GoalDiffAway = FTAG - FTHG) %>%
  group_by(Div,AwayTeam) %>%
  summarise(AwayGoalDiff = mean(GoalDiffAway))%>%
  rename(Team = AwayTeam)

combined_gd <- full_join(home_goal_diff, away_goal_diff, by = c("Team", "Div"))
goal_diff <- rbind(
  select(combined_gd, Div, Team, GD = HomeGoalDiff)%>%
    mutate(Type = "Home"),
  select(combined_gd, Div, Team, GD = AwayGoalDiff)%>%
    mutate(Type = "Away"))

goal_diff$Type <- factor(goal_diff$Type, levels = c("Home", "Away"))
```


```{r}
#Question 1
ui <- fluidPage(
  titlePanel("Home & Away Win Percentage for Teams by Division"),
  sidebarLayout(
    sidebarPanel(
      selectInput("divisionInput", "Select Division", choices = unique(combined_data$Div))
    ),
    mainPanel(
      plotOutput("winsPlot")
    )
  )
)

server <- function(input, output) {
  filtered_data <- reactive({
    combined_data %>%
      filter(Div == input$divisionInput)
  })

  output$winsPlot <- renderPlot({
    ggplot(filtered_data(), aes(x = Team, y = WinPct, fill = Type)) +
      geom_bar(stat = "identity", position = "dodge", width = 0.7) +
      labs(title = paste("Home and Away Win Rates for Each Team -", input$divisionInput),x = "Team", y = "Win Rate") +
      scale_fill_manual(values = c("blue", "red"), labels = c("Home Win Rate", "Away Win Rate")) +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip()
  })
}
shinyApp(ui, server)
```

```{r}
#Question 1 graph
ui <- fluidPage(
  titlePanel("Average Home & Away Goal Differential for Teams by Division"),
  sidebarLayout(
    sidebarPanel(
      selectInput("divisionInput", "Select Division", choices = unique(goal_diff$Div))
    ),
    mainPanel(
      plotOutput("goalsPlot")
    )
  )
)

server <- function(input, output) {
  filtered_data <- reactive({
    goal_diff %>%
      filter(Div == input$divisionInput)
  })
  output$goalsPlot <- renderPlot({
    ggplot(filtered_data(), aes(x = Team, y = GD, fill = Type)) +
    geom_bar(stat = "identity", position = "dodge", alpha = 0.7) +
    labs(x = "Team", y = "Goal Differential", title = paste("Average Home & Away Goal Differentials for Each Team -",input$divisionInput)) +
    scale_fill_manual(values = c("blue", "red"), labels = c("Home Goal Differential", "Away Goal Differential")) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  })
}
shinyApp(ui, server)
```

```{r}
#Question 2 graph
filtered_df$NetFouls = filtered_df$AF - filtered_df$HF
average_net_fouls_df <- filtered_df %>%
  unnest(cols = HomeTeam) %>%
  group_by(Div, HomeTeam) %>%
  summarize(AvgFouls = sum(NetFouls) / n())
average_net_fouls_df

ui <- fluidPage(
  titlePanel("Fouls by Team and Division"),
  sidebarLayout(
    sidebarPanel(
      selectInput("divisionInput", "Select Division", choices = unique(average_net_fouls_df$Div))
    ),
    mainPanel(
      plotOutput("foulsPlot")
    )
  )
)

# Define the server logic
server <- function(input, output) {
  filtered_data <- reactive({
    average_net_fouls_df %>%
      filter(Div == input$divisionInput)
  })

  output$foulsPlot <- renderPlot({
    ggplot(filtered_data(), aes(x = HomeTeam, y = AvgFouls, fill = HomeTeam)) +
      geom_bar(stat = "identity") +
      labs(title = paste("Net fouls against the team at home -", input$divisionInput),
           x = "Team",
           y = "Number of Fouls") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
      guides(fill = FALSE)
  })
}

# Run the Shiny app
shinyApp(ui, server)
```


```{r}
#Question 3 graph
ui <- fluidPage(
  titlePanel("Home Team Win Rate by Time"),
  sidebarLayout(
    sidebarPanel(
      selectInput("league", "Select League:", choices = unique(filtered_df$Div)),
    ),
    mainPanel(
      plotOutput("barPlot")
    )
  )
)

server <- function(input, output) {
  
  output$barPlot <- renderPlot({
    
    filtered_df <- filtered_df %>%
      rename(Result = FTR)
    
    filtered_df <- subset(filtered_df, Div == input$league)
    
    games_count <- table(filtered_df$Time)
    
    popular_time_slots <- names(games_count[games_count >= 20])
    
    filtered_df <- subset(filtered_df, Time %in% popular_time_slots)
    
    ggplot(filtered_df, aes(x = Time, fill = Result)) +
      geom_bar(position = "fill") +
      labs(title = paste("Home team win rate for every time slot with over 20 games -", input$league),
           x = "Time",
           y = "Win Rate") +
      scale_fill_manual(values = c("H" = "darkgreen", "A" = "red", "D" = "gray")) +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  })
}

shinyApp(ui = ui, server = server)
```

```{r}
#Question 3 graph
ui <- fluidPage(
  titlePanel("Games per time slot"),
  sidebarLayout(
    sidebarPanel(
      selectInput("league", "Select League:", choices = unique(filtered_df$Div)),
    ),
    mainPanel(
      plotOutput("barPlot")
    )
  )
)


server <- function(input, output) {
  
  output$barPlot <- renderPlot({
    filtered_df <- subset(filtered_df, Div == input$league)
    
    games_count <- table(filtered_df$Time)
    
    popular_time_slots <- names(games_count[games_count >= 20])
    
    filtered_df <- subset(filtered_df, Time %in% popular_time_slots)
    
    ggplot(filtered_df, aes(x = Time)) +
      geom_bar() +
      labs(title = paste("Number of Games Played in Each Time Slot -", input$league),
           x = "Time",
           y = "Number of Games") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))  # Rotate x-axis labels vertically
  })
}

shinyApp(ui = ui, server = server)
```
