
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(shiny)


df <- read.csv("all_euro_data.csv")

df_2019 <- subset(df, seq(nrow(df)) >= 197413)

df_2019_cleaned <- df_2019[-(seq(1, 4726, by = 2)), ]

filtered_df <- subset(df_2019_cleaned, select = c("Div", "Date", "Time", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "HS", "AS", "HF", "AF"))

top_5_leagues = c("E0", "D1", "SP1", "I1", "F1")

filtered_df <- filtered_df[filtered_df$Div %in% top_5_leagues, ]

filtered_df <- mutate(filtered_df, Div = recode(Div, "E0" = "Premier League", "D1" = "Bundesliga", "SP1" = "La Liga", "I1" = "Serie A", "F1" = "Ligue 1"))
```

```{r}
filtered_df$NetFouls = filtered_df$AF - filtered_df$HF
```

```{r}
average_net_fouls_df <- filtered_df %>%
  unnest(cols = HomeTeam) %>%
  group_by(Div, HomeTeam) %>%
  summarize(AvgFouls = sum(NetFouls) / n())
average_net_fouls_df
```

```{r}
ui <- fluidPage(
  titlePanel("Fouls by Team and Division"),
  sidebarLayout(
    sidebarPanel(
      selectInput("divisionInput", "Select Division", choices = unique(average_net_fouls_df$Div))
    ),
    mainPanel(
      plotOutput("foulsPlot")
    )
  )
)

# Define the server logic
server <- function(input, output) {
  filtered_data <- reactive({
    average_net_fouls_df %>%
      filter(Div == input$divisionInput)
  })

  output$foulsPlot <- renderPlot({
    ggplot(filtered_data(), aes(x = HomeTeam, y = AvgFouls, fill = HomeTeam)) +
      geom_bar(stat = "identity") +
      labs(title = paste("Net fouls by team at home -", input$divisionInput),
           x = "Team",
           y = "Number of Fouls") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
      guides(fill = FALSE)
  })
}

# Run the Shiny app
shinyApp(ui, server)
```

