```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(shiny)


df <- read.csv("all_euro_data.csv")

df_2019 <- subset(df, seq(nrow(df)) >= 197413)

df_2019_cleaned <- df_2019[-(seq(1, 4726, by = 2)), ]

filtered_df <- subset(df_2019_cleaned, select = c("Div", "Date", "Time", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "HS", "AS", "HF", "AF"))

top_5_leagues = c("E0", "D1", "SP1", "I1", "F1")

filtered_df <- filtered_df[filtered_df$Div %in% top_5_leagues, ]

filtered_df <- mutate(filtered_df, Div = recode(Div, "E0" = "Premier League", "D1" = "Bundesliga", "SP1" = "La Liga", "I1" = "Serie A", "F1" = "Ligue 1"))
```

```{r}
ui <- fluidPage(
  titlePanel("Home Team Win Rate by Time"),
  sidebarLayout(
    sidebarPanel(
      selectInput("league", "Select League:", choices = unique(filtered_df$Div)),
    ),
    mainPanel(
      plotOutput("barPlot")
    )
  )
)

server <- function(input, output) {
  
  output$barPlot <- renderPlot({
    
    filtered_df <- filtered_df %>%
      rename(Result = FTR)
    
    filtered_df <- subset(filtered_df, Div == input$league)
    
    games_count <- table(filtered_df$Time)
    
    popular_time_slots <- names(games_count[games_count >= 20])
    
    filtered_df <- subset(filtered_df, Time %in% popular_time_slots)
    
    ggplot(filtered_df, aes(x = Time, fill = Result)) +
      geom_bar(position = "fill") +
      labs(title = paste("Home team win rate for every time slot with over 20 games -", input$league),
           x = "Time",
           y = "Win Rate") +
      scale_fill_manual(values = c("H" = "darkgreen", "A" = "red", "D" = "gray")) +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  })
}

shinyApp(ui = ui, server = server)
```

```{r}
ui <- fluidPage(
  titlePanel("Games per time slot"),
  sidebarLayout(
    sidebarPanel(
      selectInput("league", "Select League:", choices = unique(filtered_df$Div)),
    ),
    mainPanel(
      plotOutput("barPlot")
    )
  )
)


server <- function(input, output) {
  
  output$barPlot <- renderPlot({
    filtered_df <- subset(filtered_df, Div == input$league)
    
    games_count <- table(filtered_df$Time)
    
    popular_time_slots <- names(games_count[games_count >= 20])
    
    filtered_df <- subset(filtered_df, Time %in% popular_time_slots)
    
    ggplot(filtered_df, aes(x = Time)) +
      geom_bar() +
      labs(title = paste("Number of Games Played in Each Time Slot -", input$league),
           x = "Time",
           y = "Number of Games") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))  # Rotate x-axis labels vertically
  })
}

shinyApp(ui = ui, server = server)
```


